2023-05-15T12:29:54 - Error executing command: Traceback (most recent call last):
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 1, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 99, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 321, in <module>
    from resource import prlimit  # python >= 3.4
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 5, in <module>
    cpu_usage = psutil.cpu_percent(interval=1)
AttributeError: partially initialized module 'psutil' has no attribute 'cpu_percent' (most likely due to a circular import)
2023-05-15T12:32:10 - Error executing command: Traceback (most recent call last):
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 1, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 99, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 321, in <module>
    from resource import prlimit  # python >= 3.4
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 5, in <module>
    cpu_usage = psutil.cpu_percent(interval=1)
AttributeError: partially initialized module 'psutil' has no attribute 'cpu_percent' (most likely due to a circular import)
2023-05-15T12:33:45 - Error executing command: Traceback (most recent call last):
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 1, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 99, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 321, in <module>
    from resource import prlimit  # python >= 3.4
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 5, in <module>
    cpu_usage = psutil.cpu_percent(interval=1)
AttributeError: partially initialized module 'psutil' has no attribute 'cpu_percent' (most likely due to a circular import)
2023-05-15T12:35:19 - Error executing command: Traceback (most recent call last):
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 1, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 99, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 321, in <module>
    from resource import prlimit  # python >= 3.4
  File "/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py", line 5, in <module>
    cpu_usage = psutil.cpu_percent(interval=1)
AttributeError: partially initialized module 'psutil' has no attribute 'cpu_percent' (most likely due to a circular import)
2023-05-15T12:36:54 - Error executing command: python: can't open file '/home/anu/assist/fantastic-assistant-Academia-/roverML/rover/resource.py': [Errno 2] No such file or directory
2023-05-15T12:38:19 - CPU usage: 5.0%
Memory usage: 42.1%
2023-05-15T12:39:55 - CPU usage: 10.7%
Memory usage: 42.2%
2023-05-15T12:41:31 - CPU usage: 18.3%
Memory usage: 42.5%
2023-05-15T12:45:38 - CPU usage: 21.9%
Memory usage: 42.9%
2023-05-15T12:47:14 - CPU usage: 4.5%
Memory usage: 43.1%
2023-05-15T12:48:49 - CPU usage: 5.0%
Memory usage: 42.9%
2023-05-15T12:50:24 - CPU usage: 4.1%
Memory usage: 42.6%
2023-05-15T12:51:59 - CPU usage: 4.5%
Memory usage: 42.8%
